# Generated by Django 3.2.13 on 2022-06-06 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=35)),
                ('proprietario', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=120)),
                ('codigo_de_barras', models.CharField(blank=True, max_length=13)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao', models.TextField()),
                ('imagem_produto', models.ImageField(upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.classificacao')),
                ('proprietario_produto', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
